import 'package:flutter/material.dart';

class GameItem {
  final String id;
  final String title;
  final String imageUrl;
  final List<String> tags;
  final double price; // current price
  final int popularity; // arbitrary score for sorting
  final Color color; // placeholder color for card art
  final String description;
  final List<String> screenshots;

  const GameItem({
    required this.id,
    required this.title,
    required this.imageUrl,
    required this.tags,
    required this.price,
    required this.popularity,
    required this.color,
    required this.description,
    required this.screenshots,
  });
}

const mockGames = <GameItem>[
  GameItem(
    id: 'gowr',
    title: 'God of War Ragnarök',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/e/ee/God_of_War_Ragnar%C3%B6k_cover.jpg',
    tags: ['Action', 'Adventure', 'Singleplayer'],
    price: 0.00,
    popularity: 9,
    color: Color(0xFF1E2A44),
    description: 'Embark on a mythic journey with Kratos and Atreus across the Nine Realms.',
    screenshots: [
      'https://upload.wikimedia.org/wikipedia/en/e/ee/God_of_War_Ragnar%C3%B6k_cover.jpg',
    ],
  ),
  // Action/RPG picks requested by user
  GameItem(
    id: 'elden-ring',
    title: 'ELDEN RING',
    imageUrl: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/capsule_616x353.jpg?t=1748630546',
    tags: ['Action', 'RPG', 'Souls-like'],
    price: 0.00,
    popularity: 9,
    color: Color(0xFF1E2A44),
    description: 'Venture into the Lands Between in this acclaimed action RPG.',
    screenshots: [
      'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/capsule_616x353.jpg?t=1748630546',
    ],
  ),
  GameItem(
    id: 'mhw',
    title: 'Monster Hunter: World',
    imageUrl: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/582010/capsule_616x353.jpg',
    tags: ['Action', 'RPG', 'Co-op'],
    price: 0.00,
    popularity: 8,
    color: Color(0xFF20304A),
    description: 'Hunt massive monsters across vast environments with friends.',
    screenshots: [
      'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/582010/capsule_616x353.jpg',
    ],
  ),
  GameItem(
    id: 'diablo4',
    title: 'Diablo IV',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1c/Diablo_IV_cover_art.png',
    tags: ['Action', 'RPG', 'Hack and Slash'],
    price: 0.00,
    popularity: 7,
    color: Color(0xFF2C3E50),
    description: 'Return to Sanctuary in a dark, open-world ARPG.',
    screenshots: [
      'https://upload.wikimedia.org/wikipedia/en/1/1c/Diablo_IV_cover_art.png',
    ],
  ),
  GameItem(
    id: 'witcher3',
    title: 'The Witcher 3: Wild Hunt',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/Witcher_3_cover_art.jpg/250px-Witcher_3_cover_art.jpg',
    tags: ['Action', 'RPG', 'Open World'],
    price: 0.00,
    popularity: 9,
    color: Color(0xFF1A2740),
    description: 'Story-rich open-world RPG starring Geralt of Rivia.',
    screenshots: [
      'https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/Witcher_3_cover_art.jpg/250px-Witcher_3_cover_art.jpg',
    ],
  ),
  GameItem(
    id: 'hzd',
    title: 'Horizon Zero Dawn',
    imageUrl: 'https://clan.akamai.steamstatic.com/images/45229080/e0683e1947ef87fbded463b25d6b09dfcb7d9b9f_400x225.png',
    tags: ['Action', 'RPG', 'Open World'],
    price: 0.00,
    popularity: 8,
    color: Color(0xFF455A64),
    description: 'Aloy\'s journey through a world ruled by machines.',
    screenshots: [
      'https://clan.akamai.steamstatic.com/images/45229080/e0683e1947ef87fbded463b25d6b09dfcb7d9b9f_400x225.png',
    ],
  ),
  // Add also to mock list so they can appear in recommendations
  GameItem(
    id: 'wuthering-waves',
    title: 'Wuthering Waves',
    imageUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/3513350/d63b9d52dd39c72fee8c43e286522640650d02b1/capsule_616x353.jpg?t=1756342405',
    tags: ['Action', 'RPG', 'Open World'],
    price: 0.00,
    popularity: 2,
    color: Color(0xFF20304A),
    description: 'Action RPG with fast-paced combat and open exploration.',
    screenshots: [
      'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/3513350/d63b9d52dd39c72fee8c43e286522640650d02b1/capsule_616x353.jpg?t=1756342405',
    ],
  ),
  GameItem(
    id: 'dbd',
    title: 'Dead by Daylight',
    imageUrl: 'https://cdn1.epicgames.com/spt-assets/2b2299be8ae84d679d4dc57c55af1510/dead-by-daylight-1hg3x.jpg',
    tags: ['Action', 'Multiplayer'],
    price: 0.00,
    popularity: 1,
    color: Color(0xFF1E2C3A),
    description: 'Asymmetric multiplayer horror where every match is a deadly game of cat and mouse.',
    screenshots: [
      'https://cdn1.epicgames.com/spt-assets/2b2299be8ae84d679d4dc57c55af1510/dead-by-daylight-1hg3x.jpg',
    ],
  ),
  GameItem(
    id: 'wukong',
    title: 'Black Myth: Wukong',
    imageUrl: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2358720/header.jpg?t=1749182199',
    tags: ['Action', 'Souls-like', 'Adventure'],
    price: 0.00,
    popularity: 2,
    color: Color(0xFF20304A),
    description: 'A next-gen action RPG inspired by Journey to the West.',
    screenshots: [
      'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2358720/header.jpg?t=1749182199',
    ],
  ),
  GameItem(
    id: 'dbsz',
    title: 'DRAGON BALL: Sparking! ZERO',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR57p5wF9dWWTQ_NSwRaZNHKZGnmtqEF1vI9A&s',
    tags: ['Action', 'Anime'],
    price: 0.00,
    popularity: 1,
    color: Color(0xFF1A2740),
    description: 'High-speed 3D battles with an enormous roster of characters.',
    screenshots: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR57p5wF9dWWTQ_NSwRaZNHKZGnmtqEF1vI9A&s',
    ],
  ),
  GameItem(
    id: 'dota2',
    title: 'Dota 2',
    imageUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/570/capsule_616x353.jpg?t=1757000652',
    tags: ['MOBA', 'Multiplayer'],
    price: 0.00,
    popularity: 7,
    color: Color(0xFF263238),
    description: 'The most-played action RTS in the world.',
    screenshots: [
      'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/570/capsule_616x353.jpg?t=1757000652',
    ],
  ),
  GameItem(
    id: 'gta5',
    title: 'Grand Theft Auto V',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR47LjFayYHU_-Hc43iGrZkvbyFmG5YXrcrmA&s',
    tags: ['Open World', 'Action', 'Adventure'],
    price: 0.00,
    popularity: 8,
    color: Color(0xFF2C3E50),
    description: 'Experience GTA Online and the epic story of Michael, Franklin, and Trevor.',
    screenshots: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR47LjFayYHU_-Hc43iGrZkvbyFmG5YXrcrmA&s',
    ],
  ),
  GameItem(
    id: 'opw4',
    title: 'ONE PIECE: PIRATE WARRIORS 4',
    imageUrl: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1089090/capsule_616x353.jpg?t=1754949684',
    tags: ['Action', 'Anime'],
    price: 0.00,
    popularity: 1,
    color: Color(0xFF1E2C3A),
    description: 'Dive into massive action set in the ONE PIECE universe.',
    screenshots: [
      'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1089090/capsule_616x353.jpg?t=1754949684',
    ],
  ),
  // Strategy Games
  GameItem(
    id: 'civilization-vi',
    title: 'Sid Meier\'s Civilization VI',
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/289070/header.jpg?t=1702315890',
    tags: ['Strategy', 'Turn-Based'],
    price: 0.00,
    popularity: 1,
    color: Color(0xFF8E24AA),
    description: 'Build an empire to stand the test of time in this turn-based strategy game.',
    screenshots: [
      'https://cdn.akamai.steamstatic.com/steam/apps/289070/header.jpg?t=1702315890',
    ],
  ),
  GameItem(
    id: 'total-war-warhammer',
    title: 'Total War: WARHAMMER III',
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1142710/header.jpg?t=1702315890',
    tags: ['Strategy', 'Real-Time'],
    price: 0.00,
    popularity: 1,
    color: Color(0xFF8E24AA),
    description: 'Command legendary heroes and vast armies in this epic strategy game.',
    screenshots: [
      'https://cdn.akamai.steamstatic.com/steam/apps/1142710/header.jpg?t=1702315890',
    ],
  ),
  GameItem(
    id: 'cities-skylines',
    title: 'Cities: Skylines',
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/255710/header.jpg?t=1702315890',
    tags: ['Simulation', 'City Builder'],
    price: 0.00,
    popularity: 1,
    color: Color(0xFF8E24AA),
    description: 'Build and manage your own city in this modern city simulation game.',
    screenshots: [
      'https://cdn.akamai.steamstatic.com/steam/apps/255710/header.jpg?t=1702315890',
    ],
  ),
  // More Sports Games
  GameItem(
    id: 'fifa-24',
    title: 'EA SPORTS FC 24',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyY_sNozclVBv_p0WK2gsblBAk9yjmz1bh5g&s',
    tags: ['Sports', 'Football'],
    price: 0.00,
    popularity: 1,
    color: Color(0xFF1E88E5),
    description: 'The world\'s game with authentic football experience.',
    screenshots: [
      'https://image.api.playstation.com/vulcan/ap/rnd/202307/1016/4b8b4b4b4b4b4b4b4b4b4b4b4b4b4b4b.png',
    ],
  ),
  GameItem(
    id: 'nba-2k24',
    title: 'NBA 2K24',
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/2338770/header.jpg?t=1702315890',
    tags: ['Sports', 'Basketball'],
    price: 0.00,
    popularity: 1,
    color: Color(0xFF1E88E5),
    description: 'Experience the most realistic basketball simulation game.',
    screenshots: [
      'https://cdn.akamai.steamstatic.com/steam/apps/2338770/header.jpg?t=1702315890',
    ],
  ),
  // More Action Games
  GameItem(
    id: 'devil-may-cry-5',
    title: 'Devil May Cry 5',
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/601150/header.jpg?t=1702315890',
    tags: ['Action', 'Hack and Slash'],
    price: 0.00,
    popularity: 1,
    color: Color(0xFFFF5722),
    description: 'Stylish action game with over-the-top combat and demon hunting.',
    screenshots: [
      'https://cdn.akamai.steamstatic.com/steam/apps/601150/header.jpg?t=1702315890',
    ],
  ),
  GameItem(
    id: 'bayonetta-3',
    title: 'Bayonetta 3',
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1446780/header.jpg?t=1702315890',
    tags: ['Action', 'Hack and Slash'],
    price: 0.00,
    popularity: 1,
    color: Color(0xFFFF5722),
    description: 'Witch with guns and magic in this stylish action adventure.',
    screenshots: [
      'https://cdn.akamai.steamstatic.com/steam/apps/1446780/header.jpg?t=1702315890',
    ],
  ),
  GameItem(
    id: 'spider-man-remastered',
    title: 'Marvel\'s Spider-Man Remastered',
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1817070/header.jpg?t=1702315890',
    tags: ['Action', 'Adventure'],
    price: 0.00,
    popularity: 2,
    color: Color(0xFFFF5722),
    description: 'Swing through New York as the iconic web-slinger.',
    screenshots: [
      'https://cdn.akamai.steamstatic.com/steam/apps/1817070/header.jpg?t=1702315890',
    ],
  ),
  // More Anime Games
  GameItem(
    id: 'persona-5-royal',
    title: 'Persona 5 Royal',
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1687950/header.jpg?t=1702315890',
    tags: ['Anime', 'RPG'],
    price: 0.00,
    popularity: 2,
    color: Color(0xFFE91E63),
    description: 'Stylish anime RPG about high school students who are phantom thieves.',
    screenshots: [
      'https://cdn.akamai.steamstatic.com/steam/apps/1687950/header.jpg?t=1702315890',
    ],
  ),
  GameItem(
    id: 'dragon-ball-fighterz',
    title: 'DRAGON BALL FighterZ',
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/678950/header.jpg?t=1702315890',
    tags: ['Anime', 'Fighting'],
    price: 0.00,
    popularity: 1,
    color: Color(0xFFE91E63),
    description: 'Epic anime fighting game featuring Dragon Ball characters.',
    screenshots: [
      'https://cdn.akamai.steamstatic.com/steam/apps/678950/header.jpg?t=1702315890',
    ],
  ),
  GameItem(
    id: 'one-piece-odyssey',
    title: 'ONE PIECE ODYSSEY',
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/814000/header.jpg?t=1702315890',
    tags: ['Anime', 'RPG'],
    price: 0.00,
    popularity: 1,
    color: Color(0xFFE91E63),
    description: 'Join Luffy and the Straw Hat Pirates in this anime RPG adventure.',
    screenshots: [
      'https://cdn.akamai.steamstatic.com/steam/apps/814000/header.jpg?t=1702315890',
    ],
  ),
  // More Shooter Games
  GameItem(
    id: 'call-of-duty-mw3',
    title: 'Call of Duty: Modern Warfare III',
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/2519060/header.jpg?t=1702315890',
    tags: ['Shooter', 'Multiplayer'],
    price: 0.00,
    popularity: 1,
    color: Color(0xFF795548),
    description: 'Intense military shooter with campaign and multiplayer modes.',
    screenshots: [
      'https://cdn.akamai.steamstatic.com/steam/apps/2519060/header.jpg?t=1702315890',
    ],
  ),
  GameItem(
    id: 'apex-legends',
    title: 'Apex Legends',
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1172470/header.jpg?t=1702315890',
    tags: ['Shooter'],
    price: 0.00,
    popularity: 1,
    color: Color(0xFF795548),
    description: 'Free-to-play battle royale hero shooter.',
    screenshots: [
      'https://cdn.akamai.steamstatic.com/steam/apps/1172470/header.jpg?t=1702315890',
    ],
  ),
  GameItem(
    id: 'overwatch-2',
    title: 'Overwatch 2',
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/2357570/header.jpg?t=1702315890',
    tags: ['Shooter', 'Hero'],
    price: 0.00,
    popularity: 1,
    color: Color(0xFF795548),
    description: 'Team-based hero shooter with unique characters and abilities.',
    screenshots: [
      'https://cdn.akamai.steamstatic.com/steam/apps/2357570/header.jpg?t=1702315890',
    ],
  ),
  GameItem(
    id: 'destiny-2',
    title: 'Destiny 2',
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1085660/header.jpg?t=1702315890',
    tags: ['Shooter', 'Looter Shooter'],
    price: 0.00,
    popularity: 1,
    color: Color(0xFF795548),
    description: 'Epic sci-fi looter shooter with raids and PvP.',
    screenshots: [
      'https://cdn.akamai.steamstatic.com/steam/apps/1085660/header.jpg?t=1702315890',
    ],
  ),
];

List<GameItem> recommendGames(List<String> preferredTags, {int max = 10}) {
  final normalized = preferredTags.map((t) => t.toLowerCase()).toSet();
  final scored = mockGames.map((g) {
    final overlap = g.tags.where((t) => normalized.contains(t.toLowerCase())).length;
    // Convert to 1-10 scale: overlap contributes 1-5 points, popularity contributes 1-5 points
    final overlapScore = (overlap / g.tags.length * 5).clamp(1.0, 5.0);
    final popularityScore = (g.popularity / 10 * 5).clamp(1.0, 5.0);
    final score = overlapScore + popularityScore;
    return (game: g, score: score);
  }).toList();
  scored.sort((a, b) => b.score.compareTo(a.score));
  return scored.take(max).map((e) => e.game).toList();
}

class CategoryItem {
  final String name;
  final String imageUrl;
  final Color accent;
  final List<String> tags;
  const CategoryItem({required this.name, required this.imageUrl, required this.accent, required this.tags});
}

const categories = <CategoryItem>[
  CategoryItem(
    name: 'Adventure',
    imageUrl: 'https://www.shutterstock.com/image-illustration/mystery-cave-scifi-building-video-600nw-496542295.jpg',
    accent: Color(0xFFE53935),
    tags: ['Adventure'],
  ),
  CategoryItem(
    name: 'Strategy',
    imageUrl: 'https://3d-ace.com/wp-content/uploads/21ap.jpeg',
    accent: Color(0xFF8E24AA),
    tags: ['Strategy'],
  ),
  CategoryItem(
    name: 'Sports',
    imageUrl: 'https://media.istockphoto.com/id/1158115722/photo/sports-and-games-background.jpg?s=170667a&w=0&k=20&c=JcnnIjPP_wVQaRKPLy5aIi536TTWxLk6xvbDHazpScQ=',
    accent: Color(0xFF1E88E5),
    tags: ['Sports'],
  ),
  CategoryItem(
    name: 'RPG',
    imageUrl: 'https://wallpapers.com/images/hd/rpg-games-1920-x-1200-wallpaper-ki7dqe23sqta5oa2.jpg',
    accent: Color(0xFF43A047),
    tags: ['RPG'],
  ),
  CategoryItem(
    name: 'Action',
    imageUrl: 'https://assets-prd.ignimgs.com/2023/12/12/turbo-overkill-1702370714781.jpeg',
    accent: Color(0xFFFF5722),
    tags: ['Action'],
  ),
  CategoryItem(
    name: 'Anime',
    imageUrl: 'https://static0.gamerantimages.com/wordpress/wp-content/uploads/2022/10/Awesome-Anime-Crossover-Games---Featured.jpg',
    accent: Color(0xFFE91E63),
    tags: ['Anime'],
  ),
  CategoryItem(
    name: 'Shooter',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQz4lg1mapIK-4bc9R3REO3glp6Y-8j9R5IOg&s',
    accent: Color(0xFF795548),
    tags: ['Shooter'],
  ),
  CategoryItem(
    name: 'Simulation',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTD3PTyoQDHh_pC6DffApqdCHYLx7YIsm0T6Q&s',
    accent: Color(0xFF607D8B),
    tags: ['Simulation'],
  ),
  CategoryItem(
    name: 'Open World',
    imageUrl: 'https://blog-uploads.eneba.games/uploads/2024/11/best-open-world-games.jpg',
    accent: Color(0xFF4CAF50),
    tags: ['Open World'],
  ),
  CategoryItem(
    name: 'MOBA',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQz4lg1mapIK-4bc9R3REO3glp6Y-8j9R5IOg&s',
    accent: Color(0xFF3F51B5),
    tags: ['MOBA'],
  ),
];

// Curated "Most Played" list requested by user
const mostPlayedGames = <GameItem>[
  GameItem(
    id: 'valorant',
    title: 'VALORANT',
    imageUrl: 'https://cdn1.epicgames.com/offer/cbd5b3d310a54b12bf3fe8c41994174f/EGS_VALORANT_RiotGames_S1_2560x1440-4f0cdb8f0cb0d06ea289ed24b28819b7',
    tags: ['Shooter', 'Multiplayer'],
    price: 0.00,
    popularity: 2,
    color: Color(0xFF1E2A44),
    description: 'Tactical 5v5 character-based shooter.',
    screenshots: [
      'https://cdn1.epicgames.com/offer/cbd5b3d310a54b12bf3fe8c41994174f/EGS_VALORANT_RiotGames_S1_2560x1440-4f0cdb8f0cb0d06ea289ed24b28819b7',
    ],
  ),
  GameItem(
    id: 'hsr',
    title: 'Honkai: Star Rail',
    imageUrl: 'https://image.api.playstation.com/vulcan/ap/rnd/202308/1103/8c3ce3611a4bb187418bb5e24924a055ba33d3046a7aaacb.png',
    tags: ['RPG', 'Anime'],
    price: 0.00,
    popularity: 2,
    color: Color(0xFF1A2740),
    description: 'Space fantasy RPG with strategic turn-based battles.',
    screenshots: [
      'https://image.api.playstation.com/vulcan/ap/rnd/202308/1103/8c3ce3611a4bb187418bb5e24924a055ba33d3046a7aaacb.png',
    ],
  ),
  GameItem(
    id: 'rocket-league',
    title: 'Rocket League',
    imageUrl: 'https://cdn1.epicgames.com/offer/9773aa1aa54f4f7b80e44bef04986cea/EGS_RocketLeague_PsyonixLLC_S1_2560x1440-4c231557ef0a0626fbb97e0bd137d837',
    tags: ['Sports', 'Racing'],
    price: 0.00,
    popularity: 2,
    color: Color(0xFF2B5D7E),
    description: 'High-powered hybrid of arcade-style soccer and vehicular mayhem.',
    screenshots: [
      'https://cdn1.epicgames.com/offer/9773aa1aa54f4f7b80e44bef04986cea/EGS_RocketLeague_PsyonixLLC_S1_2560x1440-4c231557ef0a0626fbb97e0bd137d837',
    ],
  ),
  GameItem(
    id: 'fortnite',
    title: 'Fortnite',
    imageUrl: 'https://cdn1.epicgames.com/offer/fn/FNBR_37-00_C6S4_EGS_Launcher_KeyArt_FNLogo_Blade_1200x1600_1200x1600-0924136c90b79f9006796f69f24a07f6',
    tags: ['Shooter'],
    price: 0.00,
    popularity: 2,
    color: Color(0xFF0D47A1),
    description: 'Drop in, squad up, and compete to be the last player standing.',
    screenshots: [
      'https://cdn1.epicgames.com/offer/fn/FNBR_37-00_C6S4_EGS_Launcher_KeyArt_FNLogo_Blade_1200x1600_1200x1600-0924136c90b79f9006796f69f24a07f6',
    ],
  ),
  // New Popular Games
  GameItem(
    id: 'digimon_story_time_stranger',
    title: 'Digimon Story Time Stranger',
    imageUrl: 'https://p325k7wa.twic.pics/high/digimon/digimon-story-time-stranger/00-page-setup/DSTS_header-mobile.jpg?twic=v1/resize=760/step=10/quality=80',
    tags: ['RPG', 'JRPG', 'Creature Collector', 'Party-Based RPG', 'Anime', 'Collectathon', '3D'],
    price: 2799.00,
    popularity: 2,
    color: Color(0xFF1E88E5),
    description: 'A new Digimon adventure with time-traveling mechanics and creature collection.',
    screenshots: [],
  ),
  GameItem(
    id: 'lego_party',
    title: 'LEGO® Party!',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/26/Lego_Party_cover_artwork.jpeg/250px-Lego_Party_cover_artwork.jpeg',
    tags: ['Party Game', 'LEGO', 'Party', 'Multiplayer', 'Local Multiplayer', 'Casual', '4 Player Local'],
    price: 989.95,
    popularity: 1,
    color: Color(0xFFFF9800),
    description: 'The ultimate LEGO party experience with friends and family.',
    screenshots: [],
  ),
  GameItem(
    id: 'final_fantasy_tactics_ivalice',
    title: 'FINAL FANTASY TACTICS - The Ivalice Chronicles',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQf1VWGMIFBbzJdDIJVNA3H2oGHpnUYNXlsjg&s',
    tags: ['RPG', 'Tactical RPG', 'JRPG', 'Turn-Based Tactics', 'Strategy', 'Turn-Based Strategy', 'Isometric'],
    price: 2795.00,
    popularity: 1,
    color: Color(0xFF9C27B0),
    description: 'The legendary tactical RPG returns with enhanced graphics and new content.',
    screenshots: [],
  ),
  GameItem(
    id: 'av_director_life',
    title: 'AV Director Life!',
    imageUrl: 'https://m.exophase.com/steam/games/l/136g107.png?b6b851bc7f739096015cafe30a19c4c7',
    tags: ['Simulation', 'Casual', 'Dating Sim', 'Life Sim'],
    price: 819.00,
    popularity: 1,
    color: Color(0xFFE91E63),
    description: 'Experience the life of an adult video director in this simulation game.',
    screenshots: [],
  ),
  GameItem(
    id: 'cloverpit',
    title: 'CloverPit',
    imageUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/3314790/e6955b668c667da7b5019f481707f69b4fb814b5/capsule_616x353.jpg?t=1759224878',
    tags: ['Gambling', 'Roguelite', 'Roguelike', 'Psychological Horror', 'Strategy', 'Dark Humor', '3D'],
    price: 301.50,
    popularity: 1,
    color: Color(0xFFF44336),
    description: 'A dark and twisted gambling roguelike with psychological horror elements.',
    screenshots: [],
  ),
  GameItem(
    id: 'mars_first_logistics',
    title: 'Mars First Logistics',
    imageUrl: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2465430/header.jpg?t=1726467745',
    tags: ['Stylized', 'Mars', 'Co-op', '3D', 'Building', 'Sandbox', 'Puzzle'],
    price: 369.00,
    popularity: 1,
    color: Color(0xFFFF5722),
    description: 'Build and manage logistics operations on the red planet in this sandbox puzzle game.',
    screenshots: [],
  ),
  // Additional New Games
  GameItem(
    id: 'cyberpunk_phantom_liberty',
    title: 'Cyberpunk 2077: Phantom Liberty',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6Phu-D9YdGItW1ZTj-YFeU902Qu4v8Nu1AA&s',
    tags: ['RPG', 'Action', 'Adventure', 'Sci-Fi', 'Open World', 'Story Rich', 'Futuristic'],
    price: 1999.00,
    popularity: 1,
    color: Color(0xFF673AB7),
    description: 'The highly anticipated expansion to Cyberpunk 2077 with new story content and features.',
    screenshots: [],
  ),
  GameItem(
    id: 'spider_man_2',
    title: 'Marvel\'s Spider-Man 2',
    imageUrl: 'https://image.api.playstation.com/vulcan/ap/rnd/202308/1103/8c3ce3611a4bb187418bb5e24924a055ba33d3046a7aaacb.png',
    tags: ['Action', 'Adventure', 'Superhero', 'Open World', 'Singleplayer', 'Story Rich'],
    price: 3999.00,
    popularity: 2,
    color: Color(0xFFE91E63),
    description: 'Swing through New York as both Peter Parker and Miles Morales in this epic sequel.',
    screenshots: [],
  ),
  GameItem(
    id: 'alan_wake_2',
    title: 'Alan Wake 2',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/e/ed/Alan_Wake_2_box_art.jpg',
    tags: ['Horror', 'Adventure', 'Survival Horror', 'Psychological Horror', 'Story Rich', 'Atmospheric'],
    price: 2499.00,
    popularity: 1,
    color: Color(0xFF424242),
    description: 'The long-awaited sequel to the cult classic psychological horror game.',
    screenshots: [],
  ),
  GameItem(
    id: 'starfield',
    title: 'Starfield',
    imageUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1716740/capsule_616x353.jpg?t=1749757928',
    tags: ['RPG', 'Space', 'Sci-Fi', 'Open World', 'Exploration', 'Singleplayer'],
    price: 2999.00,
    popularity: 1,
    color: Color(0xFF2196F3),
    description: 'Bethesda\'s epic space RPG set in the year 2330.',
    screenshots: [],
  ),
  GameItem(
    id: 'hogwarts_legacy',
    title: 'Hogwarts Legacy',
    imageUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/990080/header.jpg?t=1702315890',
    tags: ['RPG', 'Fantasy', 'Magic', 'Open World', 'Adventure', 'Singleplayer'],
    price: 2799.00,
    popularity: 1,
    color: Color(0xFF4CAF50),
    description: 'Experience the wizarding world in this open-world action RPG set in the 1800s.',
    screenshots: [],
  ),
  GameItem(
    id: 'diablo_4_season_3',
    title: 'Diablo IV: Season of the Construct',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR79P90K247bx8xoGCXejtn0nDhaxIENVIRtAF5ttkum2NGuk5ysGVLTcE3CIvEs-n_bIg&usqp=CAU',
    tags: ['Action', 'RPG', 'Hack and Slash', 'Loot', 'Multiplayer', 'Dark Fantasy'],
    price: 1999.00,
    popularity: 1,
    color: Color(0xFF795548),
    description: 'The latest season brings new content, items, and challenges to Sanctuary.',
    screenshots: [],
  ),
  GameItem(
    id: 'baldurs_gate_3_definitive',
    title: 'Baldur\'s Gate 3: Definitive Edition',
    imageUrl: 'https://preview.redd.it/is-the-definitive-edition-coming-v0-ihqu4o6gscpf1.jpeg?auto=webp&s=00814432ace19e374421ee5ffc13c6ea080002aa',
    tags: ['RPG', 'Turn-Based', 'Fantasy', 'Co-op', 'Story Rich', 'CRPG'],
    price: 2499.00,
    popularity: 2,
    color: Color(0xFF8BC34A),
    description: 'The complete edition of the award-winning RPG with all updates and improvements.',
    screenshots: [],
  ),
  GameItem(
    id: 'resident_evil_4_remake',
    title: 'Resident Evil 4 Remake',
    imageUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2050650/capsule_616x353.jpg?t=1736385712',
    tags: ['Horror', 'Survival Horror', 'Action', 'Third Person', 'Remake'],
    price: 2199.00,
    popularity: 1,
    color: Color(0xFFF44336),
    description: 'The classic survival horror game reimagined with modern graphics and gameplay.',
    screenshots: [],
  ),
];

// New Games for Popular New Releases section
const newGames = <GameItem>[
  GameItem(
    id: 'digimon_story_time_stranger',
    title: 'Digimon Story Time Stranger',
    imageUrl: 'https://p325k7wa.twic.pics/high/digimon/digimon-story-time-stranger/00-page-setup/DSTS_header-mobile.jpg?twic=v1/resize=760/step=10/quality=80',
    tags: ['RPG', 'JRPG', 'Creature Collector', 'Party-Based RPG', 'Anime', 'Collectathon', '3D'],
    price: 2799.00,
    popularity: 2,
    color: Color(0xFF1E88E5),
    description: 'A new Digimon adventure with time-traveling mechanics and creature collection.',
    screenshots: [],
  ),
  GameItem(
    id: 'lego_party',
    title: 'LEGO® Party!',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/26/Lego_Party_cover_artwork.jpeg/250px-Lego_Party_cover_artwork.jpeg',
    tags: ['Party Game', 'LEGO', 'Party', 'Multiplayer', 'Local Multiplayer', 'Casual', '4 Player Local'],
    price: 989.95,
    popularity: 1,
    color: Color(0xFFFF9800),
    description: 'The ultimate LEGO party experience with friends and family.',
    screenshots: [],
  ),
  GameItem(
    id: 'final_fantasy_tactics_ivalice',
    title: 'FINAL FANTASY TACTICS - The Ivalice Chronicles',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQf1VWGMIFBbzJdDIJVNA3H2oGHpnUYNXlsjg&s',
    tags: ['RPG', 'Tactical RPG', 'JRPG', 'Turn-Based Tactics', 'Strategy', 'Turn-Based Strategy', 'Isometric'],
    price: 2795.00,
    popularity: 1,
    color: Color(0xFF9C27B0),
    description: 'The legendary tactical RPG returns with enhanced graphics and new content.',
    screenshots: [],
  ),
  GameItem(
    id: 'av_director_life',
    title: 'AV Director Life!',
    imageUrl: 'https://m.exophase.com/steam/games/l/136g107.png?b6b851bc7f739096015cafe30a19c4c7',
    tags: ['Simulation', 'Casual', 'Dating Sim', 'Life Sim'],
    price: 819.00,
    popularity: 1,
    color: Color(0xFFE91E63),
    description: 'Experience the life of an adult video director in this simulation game.',
    screenshots: [],
  ),
  GameItem(
    id: 'cloverpit',
    title: 'CloverPit',
    imageUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/3314790/e6955b668c667da7b5019f481707f69b4fb814b5/capsule_616x353.jpg?t=1759224878',
    tags: ['Gambling', 'Roguelite', 'Roguelike', 'Psychological Horror', 'Strategy', 'Dark Humor', '3D'],
    price: 301.50,
    popularity: 1,
    color: Color(0xFFF44336),
    description: 'A dark and twisted gambling roguelike with psychological horror elements.',
    screenshots: [],
  ),
  GameItem(
    id: 'mars_first_logistics',
    title: 'Mars First Logistics',
    imageUrl: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2465430/header.jpg?t=1726467745',
    tags: ['Stylized', 'Mars', 'Co-op', '3D', 'Building', 'Sandbox', 'Puzzle'],
    price: 369.00,
    popularity: 1,
    color: Color(0xFFFF5722),
    description: 'Build and manage logistics operations on the red planet in this sandbox puzzle game.',
    screenshots: [],
  ),
  GameItem(
    id: 'cyberpunk_phantom_liberty',
    title: 'Cyberpunk 2077: Phantom Liberty',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6Phu-D9YdGItW1ZTj-YFeU902Qu4v8Nu1AA&s',
    tags: ['RPG', 'Action', 'Adventure', 'Sci-Fi', 'Open World', 'Story Rich', 'Futuristic'],
    price: 1999.00,
    popularity: 1,
    color: Color(0xFF673AB7),
    description: 'The highly anticipated expansion to Cyberpunk 2077 with new story content and features.',
    screenshots: [],
  ),
  GameItem(
    id: 'spider_man_2',
    title: 'Marvel\'s Spider-Man 2',
    imageUrl: 'https://ecommerce.datablitz.com.ph/cdn/shop/collections/spiderman-hotpicks_1024x.jpg?v=1697767600',
    tags: ['Action', 'Adventure', 'Superhero', 'Open World', 'Singleplayer', 'Story Rich'],
    price: 3999.00,
    popularity: 2,
    color: Color(0xFFE91E63),
    description: 'Swing through New York as both Peter Parker and Miles Morales in this epic sequel.',
    screenshots: [],
  ),
  GameItem(
    id: 'alan_wake_2',
    title: 'Alan Wake 2',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/e/ed/Alan_Wake_2_box_art.jpg',
    tags: ['Horror', 'Adventure', 'Survival Horror', 'Psychological Horror', 'Story Rich', 'Atmospheric'],
    price: 2499.00,
    popularity: 1,
    color: Color(0xFF424242),
    description: 'The long-awaited sequel to the cult classic psychological horror game.',
    screenshots: [],
  ),
  GameItem(
    id: 'starfield',
    title: 'Starfield',
    imageUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1716740/capsule_616x353.jpg?t=1749757928',
    tags: ['RPG', 'Space', 'Sci-Fi', 'Open World', 'Exploration', 'Singleplayer'],
    price: 2999.00,
    popularity: 1,
    color: Color(0xFF2196F3),
    description: 'Bethesda\'s epic space RPG set in the year 2330.',
    screenshots: [],
  ),
  GameItem(
    id: 'hogwarts_legacy',
    title: 'Hogwarts Legacy',
    imageUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/990080/22dd5a52e39a1952e77da2bd4ee49cc2e5e1a972/capsule_616x353.jpg?t=1753912780',
    tags: ['RPG', 'Fantasy', 'Magic', 'Open World', 'Adventure', 'Singleplayer'],
    price: 2799.00,
    popularity: 1,
    color: Color(0xFF4CAF50),
    description: 'Experience the wizarding world in this open-world action RPG set in the 1800s.',
    screenshots: [],
  ),
  GameItem(
    id: 'diablo_4_season_3',
    title: 'Diablo IV: Season of the Construct',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR79P90K247bx8xoGCXejtn0nDhaxIENVIRtAF5ttkum2NGuk5ysGVLTcE3CIvEs-n_bIg&usqp=CAU',
    tags: ['Action', 'RPG', 'Hack and Slash', 'Loot', 'Multiplayer', 'Dark Fantasy'],
    price: 1999.00,
    popularity: 1,
    color: Color(0xFF795548),
    description: 'The latest season brings new content, items, and challenges to Sanctuary.',
    screenshots: [],
  ),
  GameItem(
    id: 'baldurs_gate_3_definitive',
    title: 'Baldur\'s Gate 3: Definitive Edition',
    imageUrl: 'https://preview.redd.it/is-the-definitive-edition-coming-v0-ihqu4o6gscpf1.jpeg?auto=webp&s=00814432ace19e374421ee5ffc13c6ea080002aa',
    tags: ['RPG', 'Turn-Based', 'Fantasy', 'Co-op', 'Story Rich', 'CRPG'],
    price: 2499.00,
    popularity: 2,
    color: Color(0xFF8BC34A),
    description: 'The complete edition of the award-winning RPG with all updates and improvements.',
    screenshots: [],
  ),
  GameItem(
    id: 'resident_evil_4_remake',
    title: 'Resident Evil 4 Remake',
    imageUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2050650/capsule_616x353.jpg?t=1736385712',
    tags: ['Horror', 'Survival Horror', 'Action', 'Third Person', 'Remake'],
    price: 2199.00,
    popularity: 1,
    color: Color(0xFFF44336),
    description: 'The classic survival horror game reimagined with modern graphics and gameplay.',
    screenshots: [],
  ),
];

// Curated "Top Sellers" list requested by user
const topSellersGames = <GameItem>[
  GameItem(
    id: 'eafc26',
    title: 'EA SPORTS FC™ 26 Standard Edition',
    imageUrl: 'https://image.api.playstation.com/vulcan/ap/rnd/202507/1617/2e757ffb0a6bb4b91af84db64e0183d725e56e5354f45eba.png',
    tags: ['Sports', 'Football'],
    price: 0.00,
    popularity: 2,
    color: Color(0xFF1E2A44),
    description: 'The world’s game returns with clubs, leagues and tournaments.',
    screenshots: [
      'https://image.api.playstation.com/vulcan/ap/rnd/202507/1617/2e757ffb0a6bb4b91af84db64e0183d725e56e5354f45eba.png',
    ],
  ),
  GameItem(
    id: 'borderlands4',
    title: 'Borderlands®4',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/f/fd/Borderlands_4_cover_art.jpg',
    tags: ['Action', 'Looter Shooter'],
    price: 0.00,
    popularity: 2,
    color: Color(0xFF7C341F),
    description: 'Chaotic looter-shooter returns with more guns and mayhem.',
    screenshots: [
      'https://upload.wikimedia.org/wikipedia/en/f/fd/Borderlands_4_cover_art.jpg',
    ],
  ),
  GameItem(
    id: 'out-of-time',
    title: 'Out of Time',
    imageUrl: 'https://i.ytimg.com/vi/ixpS0Z06vA8/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDXTV0k1Yn2EEN9SOiesIL_kD7-Ow',
    tags: ['Adventure'],
    price: 0.00,
    popularity: 1,
    color: Color(0xFF20304A),
    description: 'An adventure where every second matters.',
    screenshots: [
      'https://i.ytimg.com/vi/ixpS0Z06vA8/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDXTV0k1Yn2EEN9SOiesIL_kD7-Ow',
    ],
  ),
  GameItem(
    id: 'dying-light-beast',
    title: 'Dying Light: The Beast',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1rr3L751n9Y4_lCp2Xka8tXa0ol7LkVe1Nw&s',
    tags: ['Action'],
    price: 0.00,
    popularity: 1,
    color: Color(0xFF2C3E50),
    description: 'Survive the night with enhanced abilities and brutal combat.',
    screenshots: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1rr3L751n9Y4_lCp2Xka8tXa0ol7LkVe1Nw&s',
    ],
  ),
];

// Virtual Reality Games
const vrGames = <GameItem>[
  GameItem(
    id: 'gorilla-tag',
    title: 'GORILLA TAG',
    imageUrl: 'https://cdn.prod.website-files.com/634dcd98720fb26a457ae36f/673756bda746759466bf6931_GT_Web-Thumb-TMUpdate.png',
    tags: ['VR', 'Multiplayer', 'Social', 'Physics'],
    price: 615.00,
    popularity: 8,
    color: Color(0xFF4CAF50),
    description: 'A physics-based multiplayer VR game where you play as a gorilla and can climb, swing, and run around.',
    screenshots: [
      'https://cdn.prod.website-files.com/634dcd98720fb26a457ae36f/673756bda746759466bf6931_GT_Web-Thumb-TMUpdate.png',
    ],
  ),
  GameItem(
    id: 'tactical-assault-vr',
    title: 'TACTICAL ASSAULT VR',
    imageUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2314160/44ef532104839797f6a5eb54b8cbe600d3d65c9c/capsule_616x353.jpg?t=1756933072',
    tags: ['VR', 'Shooter', 'Tactical', 'Military'],
    price: 565.00,
    popularity: 7,
    color: Color(0xFF795548),
    description: 'Immersive tactical military shooter designed specifically for virtual reality.',
    screenshots: [
      'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2314160/44ef532104839797f6a5eb54b8cbe600d3d65c9c/capsule_616x353.jpg?t=1756933072',
    ],
  ),
  GameItem(
    id: 'bonelab',
    title: 'BONELAB',
    imageUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1592190/capsule_616x353.jpg?t=1672959398',
    tags: ['VR', 'Physics', 'Sandbox', 'Experimental'],
    price: 1100.00,
    popularity: 8,
    color: Color(0xFF9C27B0),
    description: 'A physics-based VR game with experimental gameplay mechanics and sandbox elements.',
    screenshots: [
      'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1592190/capsule_616x353.jpg?t=1672959398',
    ],
  ),
  GameItem(
    id: 'pavlov',
    title: 'PAVLOV',
    imageUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/555160/header.jpg?t=1740613949',
    tags: ['VR', 'Shooter', 'Multiplayer', 'Tactical'],
    price: 549.95,
    popularity: 8,
    color: Color(0xFF607D8B),
    description: 'Multiplayer VR shooter with realistic weapons and tactical gameplay.',
    screenshots: [
      'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/555160/header.jpg?t=1740613949',
    ],
  ),
  GameItem(
    id: 'no-mans-sky',
    title: 'No Man\'s Sky',
    imageUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/275850/ff042a269553b2164a7575d4f445d5bd06618578/capsule_616x353_alt_assets_25.jpg?t=1758016598',
    tags: ['VR', 'Space', 'Exploration', 'Survival', 'Open World'],
    price: 1299.00,
    popularity: 9,
    color: Color(0xFF2196F3),
    description: 'Explore an infinite procedurally generated universe in virtual reality.',
    screenshots: [
      'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/275850/ff042a269553b2164a7575d4f445d5bd06618578/capsule_616x353_alt_assets_25.jpg?t=1758016598',
    ],
  ),
  GameItem(
    id: 'blade-and-sorcery',
    title: 'Blade & Sorcery',
    imageUrl: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/629730/7ae616a347df2cfb47bfa2c53aada5537b40415e/capsule_616x353.jpg?t=1759843078',
    tags: ['VR', 'Medieval', 'Combat', 'Physics', 'Sandbox'],
    price: 799.00,
    popularity: 8,
    color: Color(0xFF8D6E63),
    description: 'Medieval fantasy sandbox with physics-based combat and magic.',
    screenshots: [
      'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/629730/7ae616a347df2cfb47bfa2c53aada5537b40415e/capsule_616x353.jpg?t=1759843078',
    ],
  ),
  GameItem(
    id: 'beat-saber',
    title: 'Beat Saber',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxO6BWjxUoYuCdpvxCda66McK0amZGQ8ufug&s',
    tags: ['VR', 'Music', 'Rhythm', 'Fitness', 'Arcade'],
    price: 999.00,
    popularity: 9,
    color: Color(0xFFE91E63),
    description: 'The ultimate VR rhythm game where you slash the beats with lightsabers.',
    screenshots: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxO6BWjxUoYuCdpvxCda66McK0amZGQ8ufug&s',
    ],
  ),
  GameItem(
    id: 'vrchat',
    title: 'VRChat',
    imageUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/438100/header.jpg?t=1753401422',
    tags: ['VR', 'Social', 'Multiplayer', 'Avatar', 'Community'],
    price: 0.00,
    popularity: 8,
    color: Color(0xFF9C27B0),
    description: 'A social VR platform where you can create, publish, and explore virtual worlds.',
    screenshots: [
      'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/438100/header.jpg?t=1753401422',
    ],
  ),
];

